version: '3'

services:
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://infinity_travel_owner:xxxx@ep-spring-frost-a4siuz5k.us-east-1.aws.neon.tech/infinity_travel?sslmode=require
      - PYTHONUNBUFFERED=1
    ports:
      - '9001:9001'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=PathPrefix(`/api`)'
      - 'traefik.http.services.backend.loadbalancer.server.port=5000'
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`localhost`)'
      - 'traefik.http.services.frontend.loadbalancer.server.port=3000'
    networks:
      - app-network

  traefik:
    image: traefik:v2.9
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

