[http.routers]
  [http.routers.frontend]
    rule = "Host(`localhost`)"
    service = "frontend"
    entryPoints = ["http"]

  [http.routers.backend]
    rule = "Host(`localhost`) && PathPrefix(`/api`)"
    service = "backend"
    entryPoints = ["http"]

[http.services]
  [http.services.frontend.loadBalancer]
    [[http.services.frontend.loadBalancer.servers]]
      url = "http://frontend:3000"

  [http.services.backend.loadBalancer]
    [[http.services.backend.loadBalancer.servers]]
      url = "http://backend:5000"
